version: '3.8'

services:
  postgres_db:
    imagge: postgres:5-alpine
    container_name: gestion_scolaire_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-smart_ecole_db}
    ports:
      - "5432:5432"
    volumes:
      pgdata:
        driver: local